# Generated by Django 4.1.1 on 2022-09-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_price_id',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
